documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'

internal:
  - changed-files:
      - any-glob-to-all-files:
          - '{.github/**,scripts/**,.claude/**,src/test/**}'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'gradle/wrapper/**'
          - 'gradlew'
          - 'gradlew.bat'
